### ISSUE TITLE
Entity 생성 - Member

### ISSUE THREAD

**Issue by ljt0815** [pridi0t/popeuling#4]
### **Entity, Repository 생성 - Member, Reply**

> Member, Reply 엔티티와 Member, Reply의 JPA Repository를 만듭니다.

<br>

### ☑ Todo

- [x]  Member, Reply에 관련된 클래스 생성
- [x]  JPA Repository 생성
- [x] 어노테이션을 규칙에 맞게 변경
- [x] PK의 컬럼이름을 `엔티티이름_id` 로 수정
